# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating Tiller secret resource file
  template: src=tiller-config-secret.yaml.j2 dest=/tmp/tiller-config-secret.yaml mode=0600

- name: Configuring Tiller
  shell: kubectl apply -f /tmp/tiller-config-secret.yaml
  args:
    executable: /bin/bash

- name: Waiting for tiller to re-start
  shell: kubectl -n kube-system get deploy tiller-deploy -o=custom-columns=A:.status.readyReplicas,B:.status.replicas --no-headers=true | tr -s " " | awk '$1 == $2 {print "READY"}'
  args:
    executable: /bin/bash
  register: result
  until: result.stdout.find("READY") != -1
  retries: 100
  delay: 60
