# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

firewall_mode: "{% if firewall_enabled %}enabled{% else %}disabled{% endif %}"
firewall_type: "{% if ansible_distribution == 'Ubuntu' %}ufw{% else %}firewalld{% endif %}"
