apiVersion: v1
kind: PersistentVolume
metadata:
  name: "registry-pv1"
  labels:
    type: registry
spec:
  capacity:
    storage: "100Gi"
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /root/data
  persistentVolumeReclaimPolicy: Retain


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "registry-pvc1"
  namespace: "openshift-image-registry"
  labels:
    type: registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "100Gi"
volumeNames: registry-pv1