apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - name: nfs-pod
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: nfsvol
      mountPath: /tmp
  restartPolicy: Always
  volumes:
  - name: nfsvol
    persistentVolumeClaim:
      claimName: lab-vol-claim
