apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-sc
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: gp3
volumeBindingMode: Immediate
allowVolumeExpansion: true