# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
docker_package_name: icp-docker-{{ docker_version }}_{{ ansible_architecture }}.bin
containerd_package_name: icp-cri-containerd-{{ containerd_version }}_{{ ansible_architecture }}.bin
cni_bin_dir: /opt/cni/bin/
cni_conf_dir: /etc/cni/net.d/
