# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Generating certificates
  hosts: localhost
  any_errors_fatal: true

  roles:
    - root-ca-certs
    - etcd-certs
    - router-certs
    - registry-certs
    - ipsec-certs
    - kubernetes-certs
    - helm-certs
