# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Restarting proxy vip manager
  hosts: proxy
  any_errors_fatal: true
  serial: "{{ rolling_update_serial | default(0) }}"

  tasks:
    - name: Restarting vip manager
      shell: docker stop $(docker ps -f name=k8s_vip-script_k8s-proxy -f name=k8s_ucarp_k8s-proxy -f name=k8s_keepalived_k8s-proxy -q); true

- name: Reloading services
  hosts: localhost

  roles:
    - service-reload
