# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating management storage
  hosts: all
  any_errors_fatal: true
  roles:
    - {role: storageclass-management, delegate_to: localhost}
    - {role: storage-management, delegate_to: localhost}
