# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating firewalld rules
  firewalld: port={{ item }} permanent=true state=enabled immediate=true
  loop: "{{ firewall_open_ports[outer_item] }}"
