# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Getting ufw status
  shell: ufw status | head -n 1 | awk -F ':' '{print $2}' | xargs
  args:
    executable: /bin/bash
  register: firewall_out

- name: Validating ufw status
  fail: msg="Please disable your firewall by running ufw disable since this installation is in firewall disabled mode."
  when: firewall_out.stdout == 'active'
