# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Configure ufw rules
  ufw: rule=allow name=OpenSSH

- name: Checking host group for nodes
  include_tasks: ufw-port.yaml
  when: inventory_hostname in (groups[outer_item] | default(groups['master']))
  loop: "{{ firewall_open_ports|flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item

- name: Enable ufw
  ufw: state=enabled
