# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating storage directory
  file: path={{ inventory_dir }}/cfc-components/storage state=directory mode=0755

- include_tasks: kafka-pv.yaml
  with_items: "{{ va_nodes }}"

- include_tasks: zookeeper-pv.yaml
  with_items: "{{ va_nodes }}"

- include_tasks: minio-pv.yaml
  with_items: "{{ va_nodes }}"
