# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Adding label to system namespaces
  shell: |
    kubectl get namespace {{ item }} || kubectl create namespace {{ item }}
    kubectl label namespace {{ item }} icp=system --overwrite=true
  args:
    executable: /bin/bash
  loop:
    - kube-system
    - cert-manager
    - istio-system
