# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

## Delete the release
- name: Removing {{ key }} chart
  shell: |
    if helm status --tls {{ key }} &>/dev/null; then
      helm delete --purge --tls --timeout={{ helm_timeout }} {{ key }}
    fi
  args:
    warn: false
    chdir: "{{ inventory_dir }}"
    executable: /bin/bash
  register: result
  until: result|succeeded
  retries: 3
  delay: 5
