# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Verifying host-groups in isolated proxies
  fail: msg="Hostgroup {{item.hostgroup}} is not defined"
  when: groups['hostgroup-' + item.hostgroup] is not defined
  loop: "{{isolated_proxies}}"
