# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating Etcd config
  shell: |
    kubectl -n kube-system create configmap {{ cluster_etcd_config }} \
      --from-literal=etcd_endpoints="{{ cluster_etcd_url }}" \
      --from-literal=etcd_ca=/etcd-secrets/etcd-ca \
      --from-literal=etcd_cert=/etcd-secrets/etcd-cert \
      --from-literal=etcd_key=/etcd-secrets/etcd-key \
      --dry-run -o yaml | kubectl apply -f -
  args:
    executable: /bin/bash

- name: Creating Etcd secret
  shell: |
    kubectl -n kube-system create secret generic {{ cluster_etcd_secret }} \
      --from-file=etcd-ca=etcd/ca.pem \
      --from-file=etcd-key=etcd/client-key.pem \
      --from-file=etcd-cert=etcd/client.pem \
      --dry-run -o yaml | kubectl apply -f -
  args:
    chdir: "{{ inventory_dir }}/cfc-certs"
    executable: /bin/bash
