kubectl create -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
EOF


# 계정이 존재한 뒤에 secret을 만들어야 적용이 되더라
# 계정이 매핑한 상태로 존재한다면 secret을 제거해도 다시 생성된다.
# annotations 을 잘보자

kubectl create -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token
EOF
