# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Enabling IPsec mesh
  hosts: all
  any_errors_fatal: true
  serial: "{{ rolling_update_serial | default(0) }}"

  roles:
    - common
    - {role: ipsec, when: (ipsec_mesh.enable|bool)}
