# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Loading PPA archive
  hosts: master
  ignore_errors: true

  roles:
    - {role: archive-addon, when: addon is defined, run_once: true, archive_addons: "{{ addon }}"}
