# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Restarting Etcd cluster
  hosts: "{{ groups['etcd'] is defined | ternary('etcd', 'master') }}"
  serial: "{{ rolling_update_serial | default(0) }}"

  tasks:
    - name: Restarting Etcd container
      shell: docker stop $(docker ps -f name=k8s_etcd_k8s-etcd- -q); true
