# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: System information collecting
  hosts: master,proxy,management,etcd,va
  any_errors_fatal: false
  gather_facts: false

  vars:
    ext_hardware: hardware
    ext_docker: docker
    ext_kubelet: kubelet

  roles:
    - {role: hc-system, when: namespace is not defined}
