# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Downloading client binaries on master nodes
  hosts: master
  ignore_errors: true
  serial: "{{ rolling_update_serial | default(0) }}"

  roles:
    - setup-cli
