# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Waiting for Kubernetes to start
  shell: kubectl -n kube-system get po &>/dev/null && echo true || echo false
  args:
    executable: /bin/bash
  delegate_to: localhost
  run_once: true
  register: ready
  until: ready.stdout|bool
  retries: 10
  delay: 60
