# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Ensuring firewalld is enabled and started
  service: name=firewalld enabled=yes state=started

- name: Checking host group for nodes
  include_tasks: firewalld-port.yaml
  when: inventory_hostname in (groups[outer_item] | default(groups['master']))
  loop: "{{ firewall_open_ports|flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
