apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
  namespace: test
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 1
    defaultRequest:
      memory: 0.5Gi
      cpu: 0.5
    max:
      memory: 2Gi
    min:
      memory: 500Mi
    type: Container