apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: test
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: 15Gi
    requests.cpu: 2
    requests.memory: 2Gi
    limits.cpu: 4
    limits.memory: 4Gi