# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Deploying kubernetes node
  hosts: all:!etcd:!master
  serial: "{{ rolling_update_serial | default(0) }}"

  roles:
    - common
    - sysctl
    - iptables
    - docker-config
    - {role: icp-registry-pull-hyperkube, when: private_registry_enabled == false and image_repo != "ibmcom" and container_runtime == "docker"}
    - kubelet-config
    - cloud-provider
    - kubelet-bootstrap
    - kubelet-service
