# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating certificate secrets
  hosts: localhost
  any_errors_fatal: true

  roles:
    - root-ca-certs-secrets
    - etcd-certs-secrets
    - router-certs-secrets
    - registry-certs-secrets
    - helm-certs-secrets
