# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Ensuring all secrets are encrypted
  hosts: all
  serial: "{{ rolling_update_serial | default(0) }}"
  tasks:
    - name: Encrypting all secrets
      shell: kubectl get secrets --all-namespaces -o json | kubectl replace -f -
      delegate_to: localhost
      run_once: true
