# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Deploying environment isolation
  hosts: localhost
  max_fail_percentage: 0
  any_errors_fatal: true

  roles:
    - {role: tiller-post-config, when: isolated_proxies | length > 0}
