# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Removing local files
  file: path={{ item }} state=absent
  with_items:
    - "{{ inventory_dir }}/cfc-certs"
    - "{{ inventory_dir }}/cfc-keys"
    - "{{ inventory_dir }}/cfc-components"
    - "{{ inventory_dir }}/.install-{{ version }}.lock"
    - "{{ inventory_dir }}/conf"
    - "{{ inventory_dir }}/.addon"
    - "{{ inventory_dir }}/.misc"
