# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Removing ufw rules
  ufw: port={{ item.split('/')[0].replace('-', ':') }} proto={{ item.split('/')[1] }} rule=allow delete=yes state=reset
  loop: "{{ firewall_open_ports[outer_item] }}"
