# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Checking if kube-config exist or not
  shell: |
    if [[ -f {{ inventory_dir }}/kubeconfig ]]; then
      echo "use-exist.yaml"
    else
      echo "create-one.yaml"
    fi
  args:
    executable: /bin/bash
  register: kubeconfig
  delegate_to: localhost
  run_once: true

- include_tasks: "{{ kubeconfig.stdout }}"
