# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Configuring kubectl
  shell: |
    mkdir -p ~/.kube
    cp {{ inventory_dir }}/kubeconfig ~/.kube/config
  args:
    warn: false
    executable: /bin/bash
  delegate_to: localhost
  run_once: true
