# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- include: ipsec-mesh.yaml

- include: "{% if hostvars[groups['master'][0]]['ansible_distribution'] in ['RedHat'] %}ipsec-mesh-libreswan.yaml{% else %}ipsec-mesh-strongswan.yaml{% endif %}"
