# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating Keepalived static pod
  template: src=keepalived.json.j2 dest=/etc/cfc/pods/{{ vip_node_type }}-keepalived.json mode=0600
