# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
# - import_tasks: stop-pods.yaml
#
# - import_tasks: recover-data.yaml

- import_tasks: start-pods.yaml
