# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating tiller-secret secret
  shell: |
    kubectl -n kube-system create secret generic tiller-secret \
      --from-file=ca.crt=root-ca/ca.crt \
      --from-file=tls.crt=helm/tiller.crt \
      --from-file=tls.key=helm/tiller.key \
      --dry-run -o yaml | kubectl apply -f -
  args:
    chdir: "{{ inventory_dir }}/cfc-certs"
    executable: /bin/bash
