root@master:~/test_yaml# cat helm-repo.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: helm-repo
  name: helm-repo
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/helm-repo
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: helm-repo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      creationTimestamp: null
      labels:
        app: helm-repo
    spec:
      containers:
      - env:
        - name: LOGROTATE
          valueFrom:
            configMapKeyRef:
              key: LOGROTATE
              name: helm-repo
        - name: LOGROTATE_CONF
          valueFrom:
            configMapKeyRef:
              key: LOGROTATE_CONF
              name: helm-repo
        image: futuregen.icp:8500/ibmcom/icp-audit-service:3.2.0
        imagePullPolicy: IfNotPresent
        name: icp-audit-service
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/systemd/journal
          name: journal
        - mountPath: /var/log/audit
          name: shared
        - mountPath: /etc/logrotate.d/audit
          name: logrotate
          subPath: audit
        - mountPath: /etc/logrotate.conf
          name: logrotate-conf
          subPath: logrotate.conf
      - env:
        - name: ISICP
          value: "true"
        - name: CLUSTER_URL
          value: https://icp-management-ingress:8443
        - name: CLUSTER_CA_DOMAIN
          value: futuregen.icp
        - name: PLATFORM_IDENTITY_PROVIDER_URL
          value: http://platform-identity-provider:4300
        - name: CLUSTER_PORT
          value: "8443"
        - name: WLP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_ID
              name: platform-oidc-credentials
        - name: WLP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_SECRET
              name: platform-oidc-credentials
        - name: WLP_REDIRECT_URL
          value: http://localhost:3001/auth/liberty/callback
        - name: PROXY_ROUTE
          value: helm-repo
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: icp-mongodb-admin
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: icp-mongodb-admin
        - name: MONGO_ISSSL
          value: "true"
        - name: MONGO_SSLCA
          value: /certs/mongodb-ca/tls.crt
        - name: MONGO_SSLCERT
          value: /certs/mongodb-client/tls.crt
        - name: MONGO_SSLKEY
          value: /certs/mongodb-client/tls.key
        - name: MONGO_DBNAME
          value: helmrepo-assets
        - name: SERVICE_NAME
          value: helm-repo
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AUDIT_ENABLED
          valueFrom:
            configMapKeyRef:
              key: AUDIT_ENABLED
              name: helm-repo
        - name: AUDIT_LOG_PATH
          valueFrom:
            configMapKeyRef:
              key: AUDIT_LOG_PATH
              name: helm-repo
        image: futuregen.icp:8500/ibmcom/icp-helm-repo:3.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/v1/livecheck
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 30
        name: helm-repo
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/readycheck
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs/mongodb-ca
          name: mongodb-ca-cert
        - mountPath: /certs/mongodb-client
          name: mongodb-client-cert
        - mountPath: /var/log/audit
          name: shared
      dnsPolicy: ClusterFirst
      nodeSelector:
        master: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: mongodb-ca-cert
        secret:
          defaultMode: 420
          secretName: cluster-ca-cert
      - name: mongodb-client-cert
        secret:
          defaultMode: 420
          secretName: icp-mongodb-client-cert
      - hostPath:
          path: /run/systemd/journal
          type: ""
        name: journal
      - emptyDir: {}
        name: shared
      - configMap:
          defaultMode: 420
          items:
          - key: LOGROTATE
            path: audit
          name: helm-repo
        name: logrotate
      - configMap:
          defaultMode: 420
          items:
          - key: LOGROTATE_CONF
            path: logrotate.conf
          name: helm-repo
        name: logrotate-conf
status: {}
