root@master:~/test_yaml# cat tiller.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"helm","name":"tiller"},"name":"tiller-deploy","namespace":"kube-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"helm","name":"tiller"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":"","seccomp.security.alpha.kubernetes.io/pod":"docker/default"},"labels":{"app":"helm","name":"tiller"}},"spec":{"containers":[{"env":[{"name":"IAM_HOST","value":"platform-identity-management"},{"name":"IAM_PORT","value":"4500"},{"name":"TILLER_HISTORY_MAX","value":"5"},{"name":"TILLER_NAMESPACE","value":"kube-system"},{"name":"TILLER_TLS_CERTS","value":"/etc/certs"},{"name":"TILLER_TLS_VERIFY","value":"1"},{"name":"TILLER_TLS_ENABLE","value":"1"},{"name":"CIPHERSUITES","value":""},{"name":"default_admin_user","value":"admin"},{"name":"CLUSTER_PORT","value":"8443"}],"image":"futuregen.icp:8500/ibmcom/tiller:v2.12.3-icp-3.2.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/liveness","port":44135,"scheme":"HTTP"},"initialDelaySeconds":1,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"tiller","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/readiness","port":44135,"scheme":"HTTP"},"initialDelaySeconds":1,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/etc/certs","name":"tiller-certs"}]}],"dnsPolicy":"ClusterFirstWithHostNet","hostNetwork":true,"nodeSelector":{"master":"true"},"restartPolicy":"Always","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"dedicated","operator":"Exists"},{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoSchedule","key":"node.kubernetes.io/not-ready","operator":"Exists"}],"volumes":[{"name":"tiller-certs","secret":{"secretName":"tiller-secret"}}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/tiller-deploy
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: helm
      name: tiller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - env:
        - name: IAM_HOST
          value: platform-identity-management
        - name: IAM_PORT
          value: "4500"
        - name: TILLER_HISTORY_MAX
          value: "5"
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_TLS_CERTS
          value: /etc/certs
        - name: TILLER_TLS_VERIFY
          value: "1"
        - name: TILLER_TLS_ENABLE
          value: "1"
        - name: CIPHERSUITES
        - name: default_admin_user
          value: admin
        - name: CLUSTER_PORT
          value: "8443"
        image: futuregen.icp:8500/ibmcom/tiller:v2.12.3-icp-3.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /liveness
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: tiller
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/certs
          name: tiller-certs
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        master: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      volumes:
      - name: tiller-certs
        secret:
          defaultMode: 420
          secretName: tiller-secret
status: {}
