---
apiVersion: v1
kind: ConfigMap
metadata:
  name: icp-pod-security-policy
  namespace: kube-system
data:
  icp-pod-security-policy.json: |
   [{
      "apiVersion": "extensions/v1beta1",
      "kind": "PodSecurityPolicy",
      "metadata": {
        "annotations": {
          "kubernetes.io/description": "This policy is the most restrictive, requiring pods to run with a non-root UID, and preventing pods from accessing the host.",
          "apparmor.security.beta.kubernetes.io/allowedProfileNames": "runtime/default",
          "apparmor.security.beta.kubernetes.io/defaultProfileName": "runtime/default",
          "seccomp.security.alpha.kubernetes.io/allowedProfileNames": "docker/default",
          "seccomp.security.alpha.kubernetes.io/defaultProfileName": "docker/default"
        },
        "name": "ibm-restricted-psp"
      },
      "spec": {
        "allowPrivilegeEscalation": false,
        "forbiddenSysctls": [
          "*"
        ],
        "fsGroup": {
          "ranges": [
            {
              "max": 65535,
              "min": 1
            }
          ],
          "rule": "MustRunAs"
        },
        "requiredDropCapabilities": [
          "ALL"
        ],
        "runAsUser": {
          "rule": "MustRunAsNonRoot"
        },
        "seLinux": {
          "rule": "RunAsAny"
        },
        "supplementalGroups": {
          "ranges": [
            {
              "max": 65535,
              "min": 1
            }
          ],
          "rule": "MustRunAs"
        },
        "volumes": [
          "configMap",
          "emptyDir",
          "projected",
          "secret",
          "downwardAPI",
          "persistentVolumeClaim"
        ]
      }
    },
    {
      "apiVersion": "extensions/v1beta1",
      "kind": "PodSecurityPolicy",
      "metadata": {
        "annotations": {
          "kubernetes.io/description": "This policy allows pods to run with any UID and GID, but preventing access to the host."
        },
        "name": "ibm-anyuid-psp"
      },
      "spec": {
        "allowPrivilegeEscalation": true,
        "fsGroup": {
          "rule": "RunAsAny"
        },
        "requiredDropCapabilities": [
          "MKNOD"
        ],
        "allowedCapabilities": [
          "SETPCAP",
          "AUDIT_WRITE",
          "CHOWN",
          "NET_RAW",
          "DAC_OVERRIDE",
          "FOWNER",
          "FSETID",
          "KILL",
          "SETUID",
          "SETGID",
          "NET_BIND_SERVICE",
          "SYS_CHROOT",
          "SETFCAP"
        ],
        "runAsUser": {
          "rule": "RunAsAny"
        },
        "seLinux": {
          "rule": "RunAsAny"
        },
        "supplementalGroups": {
          "rule": "RunAsAny"
        },
        "volumes": [
          "configMap",
          "emptyDir",
          "projected",
          "secret",
          "downwardAPI",
          "persistentVolumeClaim"
        ],
        "forbiddenSysctls": [
          "*"
        ]
      }
    },
    {
      "apiVersion": "extensions/v1beta1",
      "kind": "PodSecurityPolicy",
      "metadata": {
        "annotations": {
          "kubernetes.io/description": "This policy allows pods to run with any UID and GID and any volume, including the host path. WARNING:  This policy allows hostPath volumes. Use with caution."
        },
        "name": "ibm-anyuid-hostpath-psp"
      },
      "spec": {
        "allowPrivilegeEscalation": true,
        "fsGroup": {
          "rule": "RunAsAny"
        },
        "requiredDropCapabilities": [
          "MKNOD"
        ],
        "allowedCapabilities": [
          "SETPCAP",
          "AUDIT_WRITE",
          "CHOWN",
          "NET_RAW",
          "DAC_OVERRIDE",
          "FOWNER",
          "FSETID",
          "KILL",
          "SETUID",
          "SETGID",
          "NET_BIND_SERVICE",
          "SYS_CHROOT",
          "SETFCAP"
        ],
        "runAsUser": {
          "rule": "RunAsAny"
        },
        "seLinux": {
          "rule": "RunAsAny"
        },
        "supplementalGroups": {
          "rule": "RunAsAny"
        },
        "volumes": [
          "*"
        ]
      }
    },
    {
      "apiVersion": "extensions/v1beta1",
      "kind": "PodSecurityPolicy",
      "metadata": {
        "annotations": {
          "kubernetes.io/description": "This policy allows pods to run with any UID and GID, any volume and full access to the host. WARNING:  This policy allows full access to the host and network. Use with caution."
        },
        "name": "ibm-anyuid-hostaccess-psp"
      },
      "spec": {
        "allowPrivilegeEscalation": true,
        "fsGroup": {
          "rule": "RunAsAny"
        },
        "requiredDropCapabilities": [
          "MKNOD"
        ],
        "allowedCapabilities": [
          "SETPCAP",
          "AUDIT_WRITE",
          "CHOWN",
          "NET_RAW",
          "DAC_OVERRIDE",
          "FOWNER",
          "FSETID",
          "KILL",
          "SETUID",
          "SETGID",
          "NET_BIND_SERVICE",
          "SYS_CHROOT",
          "SETFCAP"
        ],
        "runAsUser": {
          "rule": "RunAsAny"
        },
        "seLinux": {
          "rule": "RunAsAny"
        },
        "supplementalGroups": {
          "rule": "RunAsAny"
        },
        "volumes": [
          "*"
        ],
        "hostIPC": true,
        "hostNetwork": true,
        "hostPID": true,
        "hostPorts": [
          {
            "max": 65535,
            "min": 0
          }
        ]
      }
    },
    {
      "apiVersion": "extensions/v1beta1",
      "kind": "PodSecurityPolicy",
      "metadata": {
        "annotations": {
          "kubernetes.io/description": "This policy grants access to all privileged host features and allows a pod to run with any UID and GID and any volume. WARNING:  This policy is the least restrictive and should only used for cluster administration. Use with caution.",
          "seccomp.security.alpha.kubernetes.io/allowedProfileNames": "*"
        },
        "name": "ibm-privileged-psp"
      },
      "spec": {
        "allowPrivilegeEscalation": true,
        "allowedCapabilities": [
          "*"
        ],
        "allowedUnsafeSysctls": [
          "*"
        ],
        "fsGroup": {
          "rule": "RunAsAny"
        },
        "hostIPC": true,
        "hostNetwork": true,
        "hostPID": true,
        "hostPorts": [
          {
            "max": 65535,
            "min": 0
          }
        ],
        "privileged": true,
        "runAsUser": {
          "rule": "RunAsAny"
        },
        "seLinux": {
          "rule": "RunAsAny"
        },
        "supplementalGroups": {
          "rule": "RunAsAny"
        },
        "volumes": [
          "*"
        ]
      }
    }
   ]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: icp-psp-clusterrole
  namespace: kube-system
data:
  icp-psp-clusterrole.json: |
    [
     {
       "apiVersion": "rbac.authorization.k8s.io/v1",
       "kind": "ClusterRole",
       "metadata": {
         "annotations": null,
         "name": "ibm-restricted-clusterrole"
       },
       "rules": [
         {
           "apiGroups": [
             "extensions"
           ],
           "resourceNames": [
             "ibm-restricted-psp"
           ],
           "resources": [
             "podsecuritypolicies"
           ],
           "verbs": [
             "use"
           ]
         }
       ]
     },
     {
       "apiVersion": "rbac.authorization.k8s.io/v1",
       "kind": "ClusterRole",
       "metadata": {
         "annotations": null,
         "name": "ibm-anyuid-clusterrole"
       },
       "rules": [
         {
           "apiGroups": [
             "extensions"
           ],
           "resourceNames": [
             "ibm-anyuid-psp"
           ],
           "resources": [
             "podsecuritypolicies"
           ],
           "verbs": [
             "use"
           ]
         }
       ]
     },
     {
       "apiVersion": "rbac.authorization.k8s.io/v1",
       "kind": "ClusterRole",
       "metadata": {
         "annotations": null,
         "name": "ibm-anyuid-hostpath-clusterrole"
       },
       "rules": [
         {
           "apiGroups": [
             "extensions"
           ],
           "resourceNames": [
             "ibm-anyuid-hostpath-psp"
           ],
           "resources": [
             "podsecuritypolicies"
           ],
           "verbs": [
             "use"
           ]
         }
       ]
     },
     {
       "apiVersion": "rbac.authorization.k8s.io/v1",
       "kind": "ClusterRole",
       "metadata": {
         "annotations": null,
         "name": "ibm-anyuid-hostaccess-clusterrole"
       },
       "rules": [
         {
           "apiGroups": [
             "extensions"
           ],
           "resourceNames": [
             "ibm-anyuid-hostaccess-psp"
           ],
           "resources": [
             "podsecuritypolicies"
           ],
           "verbs": [
             "use"
           ]
         }
       ]
     },
     {
       "apiVersion": "rbac.authorization.k8s.io/v1",
       "kind": "ClusterRole",
       "metadata": {
         "annotations": null,
         "name": "ibm-privileged-clusterrole"
       },
       "rules": [
         {
           "apiGroups": [
             "extensions"
           ],
           "resourceNames": [
             "ibm-privileged-psp"
           ],
           "resources": [
             "podsecuritypolicies"
           ],
           "verbs": [
             "use"
           ]
         }
       ]
     }
    ]
