# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Getting Heketi Deployment name
  shell: kubectl -n kube-system get deployment -l  glusterfs=heketi-deployment -o jsonpath='{.items[0].metadata.name}'
  register: heketi_deployment
  args:
    executable: /bin/bash

- name: Waiting for Heketi Deployment to start
  shell: kubectl -n kube-system get deployment {{ heketi_deployment.stdout }} -o custom-columns=A:.status.replicas,B:.status.readyReplicas --no-headers=true | tr -s " " | awk '$1 == $2 {print "READY"}'
  args:
    executable: /bin/bash
  register: result
  until: result.stdout.find("READY") != -1
  retries: 100
  delay: 60
