# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Waiting for iam apikey secret
  shell: kubectl get secret icp-serviceid-apikey-secret -n kube-system
  args:
    executable: /bin/bash
  register: result
  until: result.stdout.find("Opaque") != -1
  retries: 5
  delay: 60
