# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: icp:teamadmin
rules:
  -
    apiGroups:
      - authorization.openshift.io
    resources:
      - clusterrolebindings
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  -
    apiGroups:
      - user.openshift.io
    resources:
      - users
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  -
    apiGroups:
      - user.openshift.io
    resources:
      - groups
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extension
rules:
  -
    nonResourceURLs:
      - "*"
    verbs:
      - "*"
  -
    apiGroups:
      - ""
    resourceNames:
      - heapster
      - "helm:api"
      - unified-router
    resources:
      - services
    verbs:
      - proxy
  -
    apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - watch
      - list
  -
    apiGroups:
      - servicecatalog.k8s.io
    resources:
      - clusterservicebrokers
      - clusterserviceclasses
      - clusterserviceplans
    verbs:
      - get
      - list
      - watch
