# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- include_tasks: ../roles/etcd/tasks/copy-client-certs.yaml

- name: Creating vip manager static pod
  template: src=vip-script.json.j2 dest=/etc/cfc/pods/{{ vip_node_type }}-vip-script.json mode=0600
