apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-test
  namespace: test
  labels:
    type: test
spec:
  replicas: 1
  selector:
    matchLabels:
      type: test
  template:
    metadata:
      labels:
        type: test
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: car-vol
          mountPath: /etc/cars
      volumes:
      - name: car-vol
        configMap:
          name: fast-car
      - name: fast-car-storage
        persistentVolumeClaim:
          claimName: pvc1
      nodeSelector:
        status: slave1
