apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: car-vol
      mountPath: /etc/cars
  volumes:
  - name: car-vol
    configMap:
      name: fast-car
  - name: fast-car-storage
    persistentVolumeClaim:
      claimName: pvc25
  tolerations:
  - key: status
    operator: Equal
    value: slave1
    effect: NoSchedule
