# openldap.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-config-pvc          # config를 위한 pvc
  namespace: <namespace>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-nfs-app

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data-pvc            # data를 위한 pvc
  namespace: <namespace>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-nfs-app

---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: <namespace>
  labels:
    app: ldap
spec:
  ports:
  - protocol: TCP
    port: 389
    targetPort: 389
  selector:
    app: ldap

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: <namespace>
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      volumes:
      - name: ldap-data
        persistentVolumeClaim:
          claimName: ldap-data-pvc
      - name: ldap-config
        persistentVolumeClaim:
          claimName: ldap-config-pvc
      containers:
      - name: ldap
        image: <cluster>:8500/default/osixia/openldap:1.2.4-dev
        args:
        - "--loglevel"
        - debug
        ports:
        - containerPort: 389
          protocol: TCP
        - containerPort: 636
          protocol: TCP
        env:
        - name: LDAP_LOG_LEVEL
          value: '256'
        - name: LDAP_ORGANISATION
          value: Example Inc.
        - name: LDAP_DOMAIN
          value: <domain info>
        - name: LDAP_ADMIN_PASSWORD
          value: password
        - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
          value: 'false'
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: ldap-data
          mountPath: "/var/lib/ldap"
        - name: ldap-config
          mountPath: "/etc/ldap/slapd.d"
