# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
- name: Rollback /etc/cfc/conf
  shell: |
    if [[ -d {{ backup_dir }}/conf ]]; then
      cp -rf {{ backup_dir }}/conf/* /etc/cfc/conf/
    fi
