# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating VA Kafka storage class
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: kafka-storage
      provisioner: "{{ storage_provisioner }}"
      volumeBindingMode: WaitForFirstConsumer
      EOF
  args:
    executable: /bin/bash

- name: Creating VA Zookeeper storage class
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: zookeeper-storage
      provisioner: "{{ storage_provisioner }}"
      volumeBindingMode: WaitForFirstConsumer
      EOF
  args:
    executable: /bin/bash

- name: Creating VA minio storage class
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: minio-storage
      provisioner: "{{ storage_provisioner }}"
      volumeBindingMode: WaitForFirstConsumer
      EOF
  args:
    executable: /bin/bash
