# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
- name: Copy old kube-proxy pod file
  copy:
    src: "{{ backup_dir }}/pods/kube-proxy.json"
    dest: /etc/cfc/pods/kube-proxy.json
    remote_src: yes
