# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Collecting facts
  hosts: "master:{{ groups['management'] is defined | ternary('management', '') }}:{{ groups['va'] is defined | ternary('va', '') }}"
  max_fail_percentage: 100
  any_errors_fatal: false

- import_playbook: plays/local-addon.yaml
