# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---


- name: Rollback docker engine
  hosts: all
  serial: 1
  force_handlers: True

  roles:
    - {role: rollback-docker-check}
    - {role: kubectl-config}
    - {role: cordon, when: installer_out.stdout == 'no' and (not_rollback|skipped)}
    - {role: drain, when: installer_out.stdout == 'no' and (not_rollback|skipped)}
    - {role: rollback-docker, when: installer_out.stdout == 'no' and (not_rollback|skipped)}
    - {role: uncordon, when: installer_out.stdout == 'no' and (not_rollback|skipped)}
