# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Uninstalling cluster nodes
  hosts: all
  serial: "{{ rolling_update_serial | default(0) }}"

  vars:
    firewall_type: "{% if ansible_distribution == 'Ubuntu' %}ufw{% else %}firewalld{% endif %}"

  roles:
    - kubectl-config
    - uninstall
