# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating Zookeeper pv file
  template: src=zookeeper.yaml.j2 dest={{ inventory_dir }}/cfc-components/storage/va-zookeeper-{{ item }}.yaml mode=0644

- name: Creating Zookeeper persistent volume
  shell: kubectl apply -f {{ inventory_dir }}/cfc-components/storage/va-zookeeper-{{ item }}.yaml
  args:
    executable: /bin/bash

- name: Creating Zookeeper persistent directory
  file: path={{ va_zookeeper_storage_dir }} state=directory mode=0755
  delegate_to: "{{ item }}"
