# https://kubernetes.io/ko/docs/tasks/inject-data-application/define-command-argument-container/
apiVersion: v1
kind: Pod
metadata:
  name: debug-alpine
  labels:
    type: debug
    owner: raphael
spec:
  serviceAccountName: legacy-app
  containers:
    - name: debug
      image: raphael9292/alpine-etc:1.1
      # command: ["/bin/sh"]
      # args: ["-c", "apk add shadow; echo test-complete; sleep 1000"]
      command:
        - sleep
      args:
        - '86400'
      resources:
        requests:
          cpu: '50m'
          memory: '64Mi'
        limits:
          cpu: '100m'
          memory: '128Mi'
  restartPolicy: Always
