# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating Etcd conf directory
  file: path=/etc/cfc/conf/etcd state=directory mode=0700

- name: Copying Etcd certificates to Etcd conf directory
  copy: src={{ inventory_dir }}/cfc-certs/etcd/{{ item }} dest=/etc/cfc/conf/etcd/{{ item }} mode=0600
  loop:
    - ca.pem
    - ca-key.pem
    - client.pem
    - client-key.pem
    - server.pem
    - server-key.pem
    - "member-{{ inventory_hostname }}.pem"
    - "member-{{ inventory_hostname }}-key.pem"
