apiVersion: v1
kind: Service
metadata:
  name: zk-test-discovery
  labels:
    app: zk-test
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zk-test