apiVersion: v1
kind: Service
metadata:
  name: zk-test-client
  labels:
    app: zk-test
spec:
  type: NodePort
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  selector:
    app: zk-test