# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Checking if Cgroup Driver of docker is set to systemd
  shell: docker info | awk '/^Cgroup Driver:/ {print $NF}'
  args:
    executable: /bin/bash
  register: info
  changed_when: false

- name: Getting cgdriver flag
  set_fact: cgdriver="{{ info.stdout }}"
