# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Validating ports
  icp_port: hosts="{{ ansible_all_ipv4_addresses }}" port="{{ item }}" state=closed
  with_items:
    - 4001
    - 2380
    - "{{ kube_apiserver_secure_port }}"
    - 8500
    - 8600
    - "{{ router_http_port }}"
    - "{{ router_https_port }}"
    - 9443
    - "{{ ingress_http_port }}"
    - "{{ ingress_https_port }}"
    - 500
    - 4500
    - 179
    - 9099
    - 10248
    - 10249
    - 10250
    - 10251
    - 10252
