# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- import_playbook: plays/environment-isolation-check.yaml

- import_playbook: plays/environment-isolation-pre-config.yaml

- import_playbook: plays/environment-isolation.yaml

- import_playbook: plays/environment-isolation-post-config.yaml
