# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
# Backup for upgrade
- import_playbook: plays/upgrade-backup.yaml
  when: inventory_hostname in worker_nodes

# Loading images
- import_playbook: plays/all-runtime-image.yaml
  when: inventory_hostname in worker_nodes

# Upgrade kubelet on all nodes
- import_playbook: plays/upgrade-kubelet.yaml
  when: inventory_hostname in worker_nodes
