# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

# Check unsupported upgrade conf
- name: Check configurations
  hosts: localhost
  force_handlers: True

  roles:
    - common
    - kubectl-config
    - upgrade-check

# For upgrade check
- import_playbook: all-check.yaml
