# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
- name: Removing Kubernetes pods buildin
  delegate_to: localhost
  shell: kubectl delete deployment,statefulset,daemonset,job -n kube-system --all
  args:
    executable: /bin/bash
  ignore_errors: true
