# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
- name: Removing node from Kubernetes
  shell: kubectl delete nodes {{ kubelet_nodename | node_name(inventory_hostname, hostvars[inventory_hostname]['ansible_'~kubelet_nodename]) }}; true

- name: Removing node from Calico
  shell: |
    ETCD_ENDPOINTS="{% for node in etcd_nodes %}https://{{ node }}:4001{% if not loop.last %},{% endif %}{% endfor %}" \
    ETCD_CERT_FILE="{{ inventory_dir }}/cfc-certs/etcd/client.pem" \
    ETCD_KEY_FILE="{{ inventory_dir }}/cfc-certs/etcd/client-key.pem" \
    ETCD_CA_CERT_FILE="{{ inventory_dir }}/cfc-certs/etcd/ca.pem" \
    calicoctl delete node {{ hostvars[inventory_hostname]['ansible_hostname'] }}
    true
  when: network_type == 'calico'
