# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating a random string for Registry
  shell: openssl rand -base64 24
  args:
    executable: /bin/bash
  register: registry_secret

- name: Ensuring that directory image-manager exist
  file: path={{ inventory_dir }}/cfc-components/image-manager/ state=directory mode=0755

- name: Ensuring that the image-manager.yaml file exist
  template: src=image-manager.yaml.j2 dest={{ inventory_dir }}/cfc-components/image-manager/image-manager.yaml mode=0644

- name: Ensuring that directory registry-conf exist
  file: path={{ inventory_dir }}/cfc-components/registry-conf/ state=directory mode=0755

- name: Ensuring that the registry configuration file exists
  template: src=registry-config.yaml.j2 dest={{ inventory_dir }}/cfc-components/registry-conf/registry-config.yaml mode=0644

- name: Creating registry configmaps
  shell: |
    kubectl -n kube-system create configmap registry-config \
      --from-file={{ inventory_dir }}/cfc-components/registry-conf/registry-config.yaml \
      --dry-run -o yaml | kubectl apply -f -
  args:
    executable: /bin/bash

- name: Deploying image-manager
  shell: kubectl apply --force --overwrite=true -f {{ inventory_dir }}/cfc-components/image-manager/
  args:
    executable: /bin/bash
