# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Fetching kubelet service status
  service:
    name: kubelet
  register: kubelet_service

- name: Stopping and disabling kubelet
  service: name=kubelet.service state=stopped
  when: kubelet_service.status.ActiveState == "active"
