# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---

- name: Creating MariaDB pv file
  template: src=mariadb.yaml.j2 dest={{ inventory_dir }}/cfc-components/storage/mariadb-{{ item }}.yaml mode=0644

- name: Creating MariaDB persistent volume
  shell: kubectl apply -f {{ inventory_dir }}/cfc-components/storage/mariadb-{{ item }}.yaml
  args:
    executable: /bin/bash

- name: Creating MariaDB persistent directory
  file: path={{ mariadb_storage_dir }} state=directory mode=0755
  delegate_to: "{{ item }}"
