# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2018 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
kind: Configuration
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
limits:
  - type: Namespace
    qps: 50
    burst: 100
    cacheSize: 2000
